### ISSUE TITLE
missing cyrillic support

### ISSUE THREAD

**Issue by hiveliberty** [SirBitesalot/AvorionServerManager#1]
Example:
`<Green0>` С‡С‚Рѕ С‚Рѕ РЅРµС‚Сѓ С‚РёС‚Р°РЅР° С…РѕС‚СЊ С‡СѓС‚СЊ С‡СѓС‚СЊ
`<hiveliberty>` РЇ РІРѕС‚ РґСѓРјР°СЋ, РЅСѓР¶РµРЅ Р»Рё РјРѕРґ РЅР° СЂРµСЃРїР°СѓРЅ Р°СЃС‚РµСЂРѕРёРґРѕРІ..
`<hiveliberty>` РќСѓ РґР°, РµРіРѕ РЅР°РґРѕ РІ СЃРѕСЃРµРґРЅРёС… СЃРµРєС‚РѕСЂР°С… РёСЃРєР°С‚СЊ
`<hiveliberty>` РќРѕ С‚СѓС‚ РІ РґРѕРјР°С€РЅРµРј РґРѕР»Р¶РµРЅ Р±С‹С‚СЊ РєСѓСЃРѕРє
`<Green0>` СЏ СѓР¶Рµ РїРѕ СЃРѕСЃРµРґСЏРј РїСЂС‹РіР°СЋ

**Comment by SirBitesalot** [comment]
@hiveliberty 
Can you describe which problems you have with cyrillic characters and where they occure?

**Comment by hiveliberty** [comment]
@SirBitesalot 
![asm01](https://cloud.githubusercontent.com/assets/16673541/22970166/92c6c6f6-f38a-11e6-8296-376f103de699.png)
This message was sent in game chat in Russian.

**Comment by SirBitesalot** [comment]
@hiveliberty 
Thank you.
I have a possible solution for this. It seems like it reads in the wrong Encoding. I  already fixed this for Broadcast commands in my local repository. 
For ingame chat I need a Test Enviroment where I can send cyrillic characters from chat (currently limited by my OS language settings it seems).
Will work on this today after work. If it all works out a fix can be expected today(Timezone CET).

**Comment by SirBitesalot** [comment]
Should be fixed now. Pre-Released a version that includes the fix.
![cyrillictest](https://cloud.githubusercontent.com/assets/22932734/22988943/2a76c32e-f3b4-11e6-9766-f2ea470f611c.JPG)
If it does not work we can reopen the issue closing it for now.
