### ISSUE TITLE
Built in Web server doesn't seem to work (Windows 10)

### ISSUE THREAD

**Issue by mikeohara** [SirBitesalot/AvorionServerManager#7]
Trying to use the built in web server on Windows 10 (running manager as administrator). Tried by letting the app through the firewall, just the port and then disabling the firewall entirely still no go. I keep getting "connection reset" when trying to visit. No errors when starting the server are reported.

Any ideas what might be wrong?

![error-remote](https://cloud.githubusercontent.com/assets/10249051/23824289/26513a88-064a-11e7-9095-13579c7a9a60.PNG)
![screenshot-error](https://cloud.githubusercontent.com/assets/10249051/23824290/265cc8f8-064a-11e7-8db2-1410769f1223.PNG)
![settings-error](https://cloud.githubusercontent.com/assets/10249051/23824291/26608010-064a-11e7-8524-b68cca675d21.PNG)

**Comment by SirBitesalot** [comment]
@mikeohara 
Did you setup an SSL certificate?
If not the help in the Tools section contains a guide to setup a self signed SSL certificate.
Normally you should get an error 404 not found with the used URL.
If you already followed the instructions try this URL to view Server Info:
[https://localhost:51234/AvorionServerManager/api/Server/](https://localhost:51234/AvorionServerManager/api/Server/)

**Comment by mikeohara** [comment]
Yep. That worked. Thanks!
