### ISSUE TITLE
When patching the Server.lua I get an error when starting the server:

### ISSUE THREAD

**Issue by mikeohara** [SirBitesalot/AvorionServerManager#8]
This is a clean version of the game, with no custom modifications to the server.lua file before applying the patch. Note: this is also NOT the beta branch, this is the stable branch. 

> 02:59:35:561 Starting up 4 worker threads.... ok
> 02:59:35:879 Loading jumping entities...Loaded 58 jumping entities.
> 02:59:35:882  ok
> 02:59:35:885 could not load script "data/scripts/server/server.lua":
> 02:59:35:888 data/scripts/server/server.lua:41: unexpected symbol near '/'
> 02:59:35:891 Setting script "data/scripts/server/server.lua" to invalid.
> 02:59:35:895 Warning: Server console commands are not supported for windows yet.

**Comment by mikeohara** [comment]
This is the modified lua file as patched by the manager. 
[server.lua.txt](https://github.com/SirBitesalot/AvorionServerManager/files/839193/server.lua.txt)

**Comment by SirBitesalot** [comment]
Error is now fixed.
File patcher  included console commands while patching the "server.lua" leading to invalid Lua syntax.
